#!/usr/bin/env python3
"""Compare magnetic reference estimation before and after nuisance correction.

The experiment starts from common cached upstream signals and reruns both
fusion passes plus magnetic nuisance correction.  This avoids comparing
caches generated by different pipeline revisions.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ProcessPoolExecutor, as_completed
import contextlib
import csv
from dataclasses import dataclass, replace
from datetime import datetime, timezone
import io
import json
from pathlib import Path
import subprocess
import sys
import time
from typing import Sequence

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[3]
BACKEND_DIR = REPO_ROOT / "backend"
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from classes.log_config import attach_log_config  # noqa: E402
from classes.time_series import TimeSeries  # noqa: E402
from log_registry import DEFAULT_REGISTRY_PATH, LogRegistry  # noqa: E402
from mag_nuisance import (  # noqa: E402
    MagNuisanceFullRateCorrection,
    MagNuisanceTravelCorrection,
)
from travel_solver_core import (  # noqa: E402
    SolverInputs,
    solve_travel,
    solver_weights_for_mag_baseline,
)
from tools.front.mag_offset_calibration.sweep_ref_point_parameters import (  # noqa: E402
    Config,
    LogData,
    aggregate_rows,
    apply_fallback,
    estimate_baseline,
    evaluate_config,
    flatten,
    load_log,
    model_for,
    rmse,
    subgroup_for_log,
    write_csv,
)


DEFAULT_TUNING_SET = "front-default"
DEFAULT_VALIDATION_SET = "slayer-filtered"
LOW_TRAVEL_MAX_MM = 30.0


@dataclass(frozen=True)
class RawInputs:
    time_s: np.ndarray
    raw_mag_mg: np.ndarray
    raw_mag_xyz_mg: np.ndarray
    gyro_dps: np.ndarray
    accel_m_s2: np.ndarray
    bad_mask: np.ndarray
    raw_prediction_mm: np.ndarray
    mag_zv_points: np.ndarray
    raw_baseline_mg: float
    processing_config: dict[str, object]


@dataclass(frozen=True)
class NuisanceResult:
    corrected_travel_mm: np.ndarray
    corrected_mag_mg: np.ndarray
    corrected_baseline_mg: float
    first_solver_mm: np.ndarray
    first_solver_success: bool
    nuisance_runtime_s: float


def git_revision() -> str | None:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    return result.stdout.strip() or None


def load_raw_inputs(
    registry: LogRegistry,
    cache_root: Path,
    log_name: str,
) -> RawInputs:
    resolved = registry.resolve(log_name)
    cache_path = cache_root / log_name / "cache" / "all.npz"
    with np.load(cache_path, allow_pickle=False) as cache:
        required = (
            "travel__t",
            "mag/norm/corr/lpf__x",
            "mag/lpf__x",
            "gyro/lpf/gyro1__x",
            "accel/lpfhp/proj__x",
            "mag/norm/bad_mask__x",
            "travel/mag_model__x",
            "mag_zv_points",
            "mag_baseline",
        )
        missing = [key for key in required if key not in cache]
        if missing:
            raise KeyError(f"{log_name}: missing cache keys {missing}")
        values = RawInputs(
            time_s=flatten(cache["travel__t"]),
            raw_mag_mg=flatten(cache["mag/norm/corr/lpf__x"]),
            raw_mag_xyz_mg=np.asarray(cache["mag/lpf__x"], dtype=float),
            gyro_dps=np.asarray(cache["gyro/lpf/gyro1__x"], dtype=float),
            accel_m_s2=flatten(cache["accel/lpfhp/proj__x"]),
            bad_mask=np.asarray(
                cache["mag/norm/bad_mask__x"], dtype=bool
            ).reshape(-1),
            raw_prediction_mm=flatten(cache["travel/mag_model__x"]),
            mag_zv_points=np.asarray(cache["mag_zv_points"], dtype=int).reshape(-1),
            raw_baseline_mg=float(flatten(cache["mag_baseline"])[0]),
            processing_config=resolved.processing_config,
        )
    lengths = {
        len(values.time_s),
        len(values.raw_mag_mg),
        len(values.raw_mag_xyz_mg),
        len(values.gyro_dps),
        len(values.accel_m_s2),
        len(values.bad_mask),
        len(values.raw_prediction_mm),
    }
    if len(lengths) != 1:
        raise ValueError(f"{log_name}: unaligned raw inputs {sorted(lengths)}")
    return values


def series(
    time_s: np.ndarray,
    values: np.ndarray,
    *,
    units: str,
    frame: str,
) -> TimeSeries:
    fs_hz = 1.0 / float(np.median(np.diff(time_s)))
    return TimeSeries(
        t=time_s,
        x=np.asarray(values),
        units=units,
        frame=frame,
        meta={"fs_hz": fs_hz},
    )


def run_solver(
    raw: RawInputs,
    prediction_mm: np.ndarray,
    mag_mg: np.ndarray,
    baseline_mg: float,
    *,
    first_pass: bool,
    max_nfev: int,
) -> tuple[np.ndarray, bool]:
    inputs = SolverInputs(
        time_s=raw.time_s,
        accel_mm_s2=raw.accel_m_s2 * 1000.0,
        mag=mag_mg,
        mag_preds_mm=prediction_mm,
        mag_zv_points=raw.mag_zv_points,
        mag_baseline=baseline_mg,
    )
    weights = solver_weights_for_mag_baseline(
        baseline_mg,
        **({"oob": 0.0} if first_pass else {}),
    )
    result = solve_travel(inputs, weights, max_nfev=max_nfev)
    return result.x, bool(result.scipy_result.success)


def run_nuisance_path(
    data: LogData,
    raw: RawInputs,
    scalar_offset_mm: float,
    *,
    max_nfev: int,
) -> NuisanceResult:
    started = time.perf_counter()
    scalar_travel = raw.raw_prediction_mm + scalar_offset_mm
    first_solver, first_success = run_solver(
        raw,
        scalar_travel,
        raw.raw_mag_mg,
        raw.raw_baseline_mg,
        first_pass=True,
        max_nfev=max_nfev,
    )
    workspace: dict[str, object] = {}
    attach_log_config(workspace, raw.processing_config)
    workspace.update(
        {
            "mag_xyz": series(
                raw.time_s,
                raw.raw_mag_xyz_mg,
                units="milli-Gauss",
                frame="mag",
            ),
            "gyro": series(raw.time_s, raw.gyro_dps, units="deg/s", frame="gyro1"),
            "raw_mag": series(
                raw.time_s,
                raw.raw_mag_mg,
                units="milli-Gauss",
                frame="gyro1",
            ),
            "coefficients": data.coefficients,
            "scalar_offset": np.array([scalar_offset_mm]),
            "initial": series(raw.time_s, first_solver, units="mm", frame="travel"),
            "scalar_travel": series(
                raw.time_s,
                scalar_travel,
                units="mm",
                frame="travel",
            ),
        }
    )
    low_step = MagNuisanceTravelCorrection(
        name="mag_nuisance_correction",
        inputs=(
            "mag_xyz",
            "gyro",
            "raw_mag",
            "coefficients",
            "scalar_offset",
            "initial",
        ),
        outputs=("low_travel", "body", "world", "xyz_path", "summary"),
    )
    full_step = MagNuisanceFullRateCorrection(
        name="mag_nuisance_full_rate",
        inputs=(
            "mag_xyz",
            "gyro",
            "initial",
            "scalar_travel",
            "low_travel",
            "body",
            "world",
            "xyz_path",
        ),
        outputs=("delta_lifted", "corrected_travel", "corrected_mag"),
    )
    with contextlib.redirect_stdout(io.StringIO()):
        low_step.run(workspace)
        full_step.run(workspace)
    corrected_travel = flatten(workspace["corrected_travel"].x)
    corrected_mag = flatten(workspace["corrected_mag"].x)
    baseline_data = replace(
        data,
        mag_mg=corrected_mag,
        base_corrected_mm=corrected_travel,
    )
    corrected_baseline, _ = estimate_baseline(
        baseline_data,
        Config(name="corrected_baseline"),
    )
    return NuisanceResult(
        corrected_travel_mm=corrected_travel,
        corrected_mag_mg=corrected_mag,
        corrected_baseline_mg=corrected_baseline,
        first_solver_mm=first_solver,
        first_solver_success=first_success,
        nuisance_runtime_s=time.perf_counter() - started,
    )


def reference_config(name: str, bump_len_s: float, max_offset_delta_mm: float) -> Config:
    return Config(
        name=name,
        family="placement",
        bump_len_s=bump_len_s,
        max_offset_delta_mm=max_offset_delta_mm,
    )


def max_offset_delta(processing_config: dict[str, object], placement: str) -> float:
    steps = processing_config.get("steps", {})
    if not isinstance(steps, dict):
        return float("inf")
    step_name = (
        "mag_to_travel_model" if placement == "pre" else "apply_mag_travel_ref_point"
    )
    step = steps.get(step_name, {})
    if not isinstance(step, dict):
        return float("inf")
    value = step.get("ref_max_offset_delta_mm")
    return float("inf") if value is None else float(value)


def raw_reference_row(
    data: LogData,
    raw: RawInputs,
    config: Config,
    chunk_cache: dict,
) -> tuple[LogData, dict[str, object]]:
    raw_data = replace(
        data,
        mag_mg=raw.raw_mag_mg,
        bad_mask=raw.bad_mask,
        base_corrected_mm=raw.raw_prediction_mm,
    )
    return raw_data, evaluate_config(raw_data, config, chunk_cache)


def fixed_offset(
    data: LogData,
    target_data: LogData,
    config: Config,
) -> tuple[float, bool, str]:
    if data.fixed_reference is None:
        raise ValueError(f"{data.log}: fixed policy requested without a reference")
    ref_x, ref_mag = data.fixed_reference
    raw_offset = ref_x - float(model_for(data).pred_x(ref_mag))
    return apply_fallback(target_data, config, raw_offset)


def metric_row(
    data: LogData,
    *,
    variant: str,
    placement: str,
    detector_signal: str,
    policy: str,
    bump_len_s: float,
    offset_mm: float,
    used_fallback: bool,
    fallback_reason: str,
    calibration_found: bool,
    n_chunks: float,
    n_ref_points: float,
    corrected_prediction: np.ndarray,
    final_prediction: np.ndarray,
    first_success: bool,
    final_success: bool,
    runtime_s: float,
) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for stage, prediction in (
        ("corrected_observation", corrected_prediction),
        ("final_solver", final_prediction),
    ):
        mask = data.eval_mask & np.isfinite(prediction) & np.isfinite(data.truth_mm)
        low = mask & (data.truth_mm >= 0.0) & (data.truth_mm < LOW_TRAVEL_MAX_MM)
        error = prediction - data.truth_mm
        rows.append(
            {
                "split": data.split,
                "cohort": data.cohort,
                "subgroup": data.subgroup,
                "log": data.log,
                "parent_log": data.parent_log,
                "stage": stage,
                "variant": variant,
                "placement": placement,
                "detector_signal": detector_signal,
                "policy": policy,
                "bump_len_s": bump_len_s,
                "offset_mm": offset_mm,
                "calibration_found": calibration_found,
                "used_fallback": used_fallback,
                "fallback_reason": fallback_reason,
                "n_chunks": n_chunks,
                "n_ref_points": n_ref_points,
                "mean_error_mm": float(np.mean(error[mask])),
                "uncentered_rmse_mm": rmse(error[mask]),
                "low_uncentered_rmse_mm": (
                    rmse(error[low]) if np.any(low) else float("nan")
                ),
                "centered_rmse_mm": rmse(error[mask] - float(np.mean(error[mask]))),
                "first_solver_success": first_success,
                "final_solver_success": final_success,
                "runtime_s": runtime_s,
            }
        )
    return rows


def evaluate_variant(
    data: LogData,
    raw: RawInputs,
    *,
    placement: str,
    detector_signal: str,
    policy: str,
    bump_len_s: float,
    zero_path: NuisanceResult,
    raw_ref_data: LogData,
    raw_ref_row: dict[str, object],
    chunk_cache: dict,
    max_nfev: int,
) -> list[dict[str, object]]:
    variant = f"{placement}_{detector_signal}_{policy}_{bump_len_s:g}s"
    cap = max_offset_delta(raw.processing_config, placement)
    config = reference_config(variant, bump_len_s, cap)
    started = time.perf_counter()

    use_fixed = policy == "registry" and data.fixed_reference is not None
    if placement == "pre":
        if use_fixed:
            offset, used_fallback, reason = fixed_offset(
                data, raw_ref_data, config
            )
            found, n_chunks, n_points = True, float("nan"), float("nan")
        else:
            offset = float(raw_ref_row["offset_mm"])
            used_fallback = bool(raw_ref_row["used_fallback"])
            reason = str(raw_ref_row["fallback_reason"])
            found = bool(raw_ref_row["calibration_found"])
            n_chunks = float(raw_ref_row["n_chunks"])
            n_points = float(raw_ref_row["n_ref_points"])
        nuisance = run_nuisance_path(
            data,
            raw,
            offset,
            max_nfev=max_nfev,
        )
        corrected_prediction = nuisance.corrected_travel_mm
    elif placement == "post":
        nuisance = zero_path
        target_data = replace(
            data,
            mag_mg=(
                raw.raw_mag_mg
                if detector_signal == "uncorrected"
                else nuisance.corrected_mag_mg
            ),
            bad_mask=raw.bad_mask,
            base_corrected_mm=nuisance.corrected_travel_mm,
        )
        if use_fixed:
            offset, used_fallback, reason = fixed_offset(data, target_data, config)
            found, n_chunks, n_points = True, float("nan"), float("nan")
        elif detector_signal == "uncorrected":
            raw_offset = (
                float(raw_ref_row["raw_offset_mm"])
                if bool(raw_ref_row["calibration_found"])
                else None
            )
            offset, used_fallback, reason = apply_fallback(
                target_data,
                config,
                raw_offset,
            )
            found = bool(raw_ref_row["calibration_found"])
            n_chunks = float(raw_ref_row["n_chunks"])
            n_points = float(raw_ref_row["n_ref_points"])
        else:
            corrected_row = evaluate_config(target_data, config, chunk_cache)
            offset = float(corrected_row["offset_mm"])
            used_fallback = bool(corrected_row["used_fallback"])
            reason = str(corrected_row["fallback_reason"])
            found = bool(corrected_row["calibration_found"])
            n_chunks = float(corrected_row["n_chunks"])
            n_points = float(corrected_row["n_ref_points"])
        corrected_prediction = nuisance.corrected_travel_mm + offset
    else:
        raise ValueError(f"unknown placement {placement!r}")

    final_prediction, final_success = run_solver(
        raw,
        corrected_prediction,
        nuisance.corrected_mag_mg,
        nuisance.corrected_baseline_mg,
        first_pass=False,
        max_nfev=max_nfev,
    )
    return metric_row(
        data,
        variant=variant,
        placement=placement,
        detector_signal=detector_signal,
        policy=policy,
        bump_len_s=bump_len_s,
        offset_mm=offset,
        used_fallback=used_fallback,
        fallback_reason=reason,
        calibration_found=found,
        n_chunks=n_chunks,
        n_ref_points=n_points,
        corrected_prediction=corrected_prediction,
        final_prediction=final_prediction,
        first_success=nuisance.first_solver_success,
        final_success=final_success,
        runtime_s=time.perf_counter() - started,
    )


def run_log(
    registry_path: str,
    cache_root: str,
    log_name: str,
    split: str,
    cohort: str,
    max_nfev: int,
) -> list[dict[str, object]]:
    registry = LogRegistry.load(Path(registry_path))
    data = load_log(
        registry,
        Path(cache_root),
        log_name,
        split=split,
        cohort=cohort,
    )
    raw = load_raw_inputs(registry, Path(cache_root), log_name)
    chunk_cache: dict = {}
    zero_path = run_nuisance_path(data, raw, 0.0, max_nfev=max_nfev)
    output: list[dict[str, object]] = []

    raw_refs: dict[float, tuple[LogData, dict[str, object]]] = {}
    for bump_len in (0.2, 0.3):
        config = reference_config(
            f"raw_reference_{bump_len:g}s",
            bump_len,
            max_offset_delta(raw.processing_config, "pre"),
        )
        raw_refs[bump_len] = raw_reference_row(data, raw, config, chunk_cache)

    # Main automatic comparison at both the selected and historical windows.
    for bump_len in (0.2, 0.3):
        raw_data, raw_row = raw_refs[bump_len]
        for placement, detector in (
            ("pre", "uncorrected"),
            ("post", "corrected"),
            # Isolates detector signal from application placement.
            ("post", "uncorrected"),
        ):
            output.extend(
                evaluate_variant(
                    data,
                    raw,
                    placement=placement,
                    detector_signal=detector,
                    policy="automatic",
                    bump_len_s=bump_len,
                    zero_path=zero_path,
                    raw_ref_data=raw_data,
                    raw_ref_row=raw_row,
                    chunk_cache=chunk_cache,
                    max_nfev=max_nfev,
                )
            )

    # Compare the actual registry fixed-reference policy where it exists.
    if data.fixed_reference is not None:
        raw_data, raw_row = raw_refs[0.2]
        for placement, detector in (
            ("pre", "uncorrected"),
            ("post", "corrected"),
        ):
            output.extend(
                evaluate_variant(
                    data,
                    raw,
                    placement=placement,
                    detector_signal=detector,
                    policy="registry",
                    bump_len_s=0.2,
                    zero_path=zero_path,
                    raw_ref_data=raw_data,
                    raw_ref_row=raw_row,
                    chunk_cache=chunk_cache,
                    max_nfev=max_nfev,
                )
            )
    return output


def aggregate_metrics(rows: Sequence[dict[str, object]]) -> list[dict[str, object]]:
    metrics = (
        "calibration_found",
        "used_fallback",
        "n_chunks",
        "n_ref_points",
        "mean_error_mm",
        "uncentered_rmse_mm",
        "low_uncentered_rmse_mm",
        "centered_rmse_mm",
        "first_solver_success",
        "final_solver_success",
        "runtime_s",
    )
    output: list[dict[str, object]] = []

    def scalar(value: object) -> float:
        if isinstance(value, str) and value.strip().lower() in {"true", "false"}:
            return float(value.strip().lower() == "true")
        return float(value)

    def safe_mean(values: Sequence[object]) -> float:
        array = np.asarray([scalar(value) for value in values], dtype=float)
        finite = array[np.isfinite(array)]
        return float(np.mean(finite)) if len(finite) else float("nan")

    for split in sorted({str(row["split"]) for row in rows}):
        split_rows = [row for row in rows if row["split"] == split]
        for stage in sorted({str(row["stage"]) for row in split_rows}):
            stage_rows = [row for row in split_rows if row["stage"] == stage]
            for variant in sorted({str(row["variant"]) for row in stage_rows}):
                selected = [row for row in stage_rows if row["variant"] == variant]
                groups = sorted({str(row["subgroup"]) for row in selected})
                group_rows = []
                for group in groups:
                    grouped = [row for row in selected if row["subgroup"] == group]
                    summary = {
                        "split": split,
                        "stage": stage,
                        "scope": group,
                        "variant": variant,
                        "placement": selected[0]["placement"],
                        "detector_signal": selected[0]["detector_signal"],
                        "policy": selected[0]["policy"],
                        "bump_len_s": selected[0]["bump_len_s"],
                        "n_logs": len(grouped),
                        **{
                            metric: safe_mean(
                                [row[metric] for row in grouped]
                            )
                            for metric in metrics
                        },
                    }
                    output.append(summary)
                    group_rows.append(summary)
                output.append(
                    {
                        "split": split,
                        "stage": stage,
                        "scope": "cohort-balanced",
                        "variant": variant,
                        "placement": selected[0]["placement"],
                        "detector_signal": selected[0]["detector_signal"],
                        "policy": selected[0]["policy"],
                        "bump_len_s": selected[0]["bump_len_s"],
                        "n_logs": len(selected),
                        **{
                            metric: safe_mean(
                                [row[metric] for row in group_rows]
                            )
                            for metric in metrics
                        },
                    }
                )
    return output


def aggregate_validation_parents(
    rows: Sequence[dict[str, object]],
) -> list[dict[str, object]]:
    metrics = (
        "mean_error_mm",
        "uncentered_rmse_mm",
        "low_uncentered_rmse_mm",
        "centered_rmse_mm",
    )
    validation = [row for row in rows if row["split"] == "validation"]
    output = []
    for stage in sorted({str(row["stage"]) for row in validation}):
        for variant in sorted({str(row["variant"]) for row in validation}):
            selected = [
                row
                for row in validation
                if row["stage"] == stage and row["variant"] == variant
            ]
            if not selected:
                continue
            parents = sorted({str(row["parent_log"]) for row in selected})
            parent_rows = [
                {
                    metric: float(
                        np.mean(
                            [
                                float(row[metric])
                                for row in selected
                                if row["parent_log"] == parent
                            ]
                        )
                    )
                    for metric in metrics
                }
                for parent in parents
            ]
            output.append(
                {
                    "stage": stage,
                    "variant": variant,
                    "n_logs": len(selected),
                    "n_parents": len(parents),
                    **{
                        metric: float(np.mean([row[metric] for row in parent_rows]))
                        for metric in metrics
                    },
                }
            )
    return output


def resolve_jobs(
    registry: LogRegistry,
    tuning_set: str,
    validation_set: str,
) -> list[tuple[str, str, str]]:
    jobs = []
    seen = set()
    for split, cohort in (("tuning", tuning_set), ("validation", validation_set)):
        logs = registry.select(set_name=cohort, usable_only=True)
        for log in logs:
            if log.pipeline != "front" or log.log_id in seen:
                raise ValueError(f"invalid or duplicated log {log.log_id}")
            seen.add(log.log_id)
            jobs.append((split, cohort, log.log_id))
    return jobs


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY_PATH)
    parser.add_argument(
        "--cache-root", type=Path, default=REPO_ROOT / "backend" / "run_artifacts"
    )
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--tuning-set", default=DEFAULT_TUNING_SET)
    parser.add_argument("--validation-set", default=DEFAULT_VALIDATION_SET)
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--max-nfev", type=int, default=100)
    parser.add_argument("--limit", type=int)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    registry = LogRegistry.load(args.registry)
    jobs = resolve_jobs(registry, args.tuning_set, args.validation_set)
    if args.limit is not None:
        jobs = jobs[: args.limit]
    args.output_dir.mkdir(parents=True, exist_ok=True)
    rows: list[dict[str, object]] = []
    if args.workers <= 1:
        for index, (split, cohort, log_name) in enumerate(jobs, 1):
            rows.extend(
                run_log(
                    str(args.registry),
                    str(args.cache_root),
                    log_name,
                    split,
                    cohort,
                    args.max_nfev,
                )
            )
            print(f"[{index}/{len(jobs)}] {split}/{log_name}", flush=True)
    else:
        with ProcessPoolExecutor(max_workers=args.workers) as executor:
            futures = {
                executor.submit(
                    run_log,
                    str(args.registry),
                    str(args.cache_root),
                    log_name,
                    split,
                    cohort,
                    args.max_nfev,
                ): (split, log_name)
                for split, cohort, log_name in jobs
            }
            for index, future in enumerate(as_completed(futures), 1):
                split, log_name = futures[future]
                rows.extend(future.result())
                print(f"[{index}/{len(jobs)}] {split}/{log_name}", flush=True)
    write_csv(args.output_dir / "per_log.csv", rows)
    write_csv(args.output_dir / "aggregate.csv", aggregate_metrics(rows))
    write_csv(
        args.output_dir / "validation_parent_aggregate.csv",
        aggregate_validation_parents(rows),
    )
    manifest = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "git_revision": git_revision(),
        "tuning_set": args.tuning_set,
        "validation_set": args.validation_set,
        "jobs": [
            {"split": split, "cohort": cohort, "log": log_name}
            for split, cohort, log_name in jobs
        ],
        "workers": args.workers,
        "max_nfev": args.max_nfev,
        "protocol": (
            "Common cached upstream signals; rerun first solver, nuisance fit, "
            "full-rate correction, reference application, and final solver."
        ),
    }
    (args.output_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
